"""add_billing_and_prescription_workflow

Revision ID: 9770400ce545
Revises: d82e374cca85
Create Date: 2026-06-08 15:38:14.797369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9770400ce545'
down_revision = 'd82e374cca85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('ccam_codes', sa.Text(), nullable=True),
    sa.Column('acts_total', sa.Float(), nullable=False),
    sa.Column('social_security_base', sa.Float(), nullable=False),
    sa.Column('social_security_paid', sa.Float(), nullable=False),
    sa.Column('mutuelle_paid', sa.Float(), nullable=False),
    sa.Column('patient_liability', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('validated_by', sa.String(length=36), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prescriptions', sa.Column('signature_hash', sa.String(length=64), nullable=True))
    op.add_column('prescriptions', sa.Column('sent_to_email', sa.String(length=100), nullable=True))
    op.add_column('prescriptions', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prescriptions', sa.Column('cancelled_by', sa.String(length=36), nullable=True))
    op.add_column('prescriptions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prescriptions', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescriptions', 'cancellation_reason')
    op.drop_column('prescriptions', 'cancelled_at')
    op.drop_column('prescriptions', 'cancelled_by')
    op.drop_column('prescriptions', 'sent_at')
    op.drop_column('prescriptions', 'sent_to_email')
    op.drop_column('prescriptions', 'signature_hash')
    op.drop_table('billings')
    # ### end Alembic commands ###
